# FROM tensorflow/tensorflow:2.4.2
FROM python:3.8

ARG USER_NAME
ARG USER_ID
ARG GROUP_ID

ENV USER ${USER_NAME}
ENV HOME /home/${USER_NAME}

# サーバーを日本に変更
# 多分早くなる
RUN sed -i 's@archive.ubuntu.com@ftp.jaist.ac.jp/pub/Linux@g' /etc/apt/sources.list

# #パッケージインストール
RUN apt-get update \
&&  apt-get install -y --no-install-recommends \
                sudo \
                git \
                make \
                cmake \
                curl \
                wget \
                xz-utils \
                #japanase
                # language-pack-ja-base \
                # language-pack-ja \
                locales 
                # cargo

# 日本語化
RUN locale-gen ja_JP.UTF-8 
ENV LANG ja_JP.UTF-8
ENV LC_CTYPE ja_JP.UTF-8
RUN localedef -f UTF-8 -i ja_JP ja_JP.utf8

## make user
RUN set -x \
&&  echo "Starting with UID : ${USER_ID}, GID: ${GROUP_ID}" \
&&  adduser --disabled-password --gecos "" "${USER_NAME}" \
&&  echo "${USER_NAME}:${USER_NAME}" | chpasswd \
&&  echo "%${USER_NAME}    ALL=(ALL)   NOPASSWD:    ALL" >> /etc/sudoers.d/${USER_NAME}  \
&&  chmod 0440 /etc/sudoers.d/${USER_NAME} \
&&  usermod -u ${USER_ID} ${USER_NAME} \
&&  groupmod -g ${GROUP_ID} ${USER_NAME} 

USER ${USER}
WORKDIR ${HOME}/workspace
ENV RUST_VERSION stable
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain ${RUST_VERSION}
ENV PATH $PATH:$HOME/.cargo/bin

RUN rustup install stable
RUN rustup install beta
RUN rustup install nightly

# RUN git clone https://github.com/WorksApplications/sudachi.rs.git sudachi.rs
# RUN set -x && \
#     cd ./sudachi.rs && \
#     cargo build --target=x86_64-apple-darwin && \ 
#     cargo build --release && \
#     cargo install --path sudachi-cli/ && \
#     ./fetch_dictionary.sh


# # python 
RUN python3 -m pip --no-cache-dir install --upgrade \
    ipywidgets \
    gensim \
    janome \
    matplotlib \
    tqdm \
    hydra-core \
    python-Levenshtein \
    sudachipy>=0.6.3 \
    ginza ja_ginza


WORKDIR ${HOME}